# Generated by Django 5.0.6 on 2024-08-01 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Conceptos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=30)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ING", "Ingreso"), ("EGR", "Egreso")], max_length=7
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[("PE", "Pesos"), ("US", "Dolares")], max_length=7
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCajas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=3)),
                ("descripcion", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="CajaDolares",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now=True)),
                ("detalle", models.CharField(max_length=30)),
                ("cotizacion", models.IntegerField()),
                ("ingreso", models.FloatField()),
                ("egreso", models.FloatField()),
                (
                    "subcaja",
                    models.CharField(
                        choices=[("CD", "Cuenta Diego"), ("CK", "Cuenta Kyle")],
                        max_length=7,
                    ),
                ),
                ("action_time", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppZorro.conceptos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AppZorro.autor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CajaPesos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now=True)),
                ("detalle", models.CharField(max_length=30)),
                ("ingreso", models.FloatField()),
                ("egreso", models.FloatField()),
                ("action_time", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "caja_dolar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppZorro.cajadolares",
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppZorro.conceptos",
                    ),
                ),
                (
                    "subcaja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppZorro.subcajas",
                    ),
                ),
            ],
        ),
    ]
