# Generated by Django 4.2 on 2024-08-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppZorro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comprobantes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comprobante",
                    models.ImageField(blank=True, null=True, upload_to="comprobantes"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rubros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=30)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ING", "Ingreso"), ("EGR", "Egreso")], max_length=7
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="cajadolares",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="cajadolares",
            name="concepto",
        ),
        migrations.RemoveField(
            model_name="libro",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="cajapesos",
            name="caja_dolar",
        ),
        migrations.RemoveField(
            model_name="cajapesos",
            name="concepto",
        ),
        migrations.RemoveField(
            model_name="cajapesos",
            name="subcaja",
        ),
        migrations.AlterField(
            model_name="cajapesos",
            name="detalle",
            field=models.CharField(max_length=60),
        ),
        migrations.DeleteModel(
            name="Autor",
        ),
        migrations.DeleteModel(
            name="CajaDolares",
        ),
        migrations.DeleteModel(
            name="Conceptos",
        ),
        migrations.DeleteModel(
            name="Libro",
        ),
        migrations.DeleteModel(
            name="SubCajas",
        ),
        migrations.AddField(
            model_name="cajapesos",
            name="comprobante",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppZorro.comprobantes",
            ),
        ),
        migrations.AddField(
            model_name="cajapesos",
            name="rubro",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppZorro.rubros",
            ),
        ),
    ]
