# Generated by Django 4.2 on 2024-08-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppZorro", "0002_comprobantes_rubros_remove_cajadolares_autor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cajapesos",
            name="egreso",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="cajapesos",
            name="ingreso",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="cajapesos",
            name="rubro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppZorro.rubros",
            ),
        ),
    ]
