# Generated by Django 4.2 on 2024-08-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppZorro", "0003_alter_cajapesos_egreso_alter_cajapesos_ingreso_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cajapesos",
            name="comprobante",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppZorro.comprobantes",
            ),
        ),
        migrations.AlterField(
            model_name="cajapesos",
            name="egreso",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cajapesos",
            name="fecha",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="cajapesos",
            name="ingreso",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
