# Generated by Django 4.2 on 2024-08-11 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppZorro", "0010_alter_cajapesos_rubro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cajapesos",
            name="rubro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="AppZorro.rubros"
            ),
        ),
    ]
