# Generated by Django 4.2 on 2024-08-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppZorro", "0013_alter_cajapesos_rubro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cajapesos",
            name="comprobante",
            field=models.ImageField(blank=True, null=True, upload_to="comprobantes"),
        ),
    ]
