# Generated by Django 4.2 on 2024-08-11 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppZorro", "0014_alter_cajapesos_comprobante"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comprobantes",
        ),
        migrations.AlterField(
            model_name="cajapesos",
            name="rubro",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="AppZorro.rubros",
            ),
        ),
    ]
