# Generated by Django 4.2 on 2024-08-14 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("AppZorro", "0015_delete_comprobantes_alter_cajapesos_rubro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cajapesos",
            name="autor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
