# Generated by Django 4.2 on 2024-08-24 22:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("AppZorro", "0016_alter_cajapesos_autor"),
    ]

    operations = [
        migrations.CreateModel(
            name="CajaDolares",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=datetime.date.today)),
                ("detalle", models.CharField(max_length=60)),
                ("cotiza", models.FloatField(default=0)),
                ("ingreso", models.FloatField(default=0)),
                ("egreso", models.FloatField(default=0)),
                ("action_time", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
