# Generated by Django 4.2 on 2024-08-30 01:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("AppZorro", "0019_rename_obras_obra_rename_tareas_tarea"),
    ]

    operations = [
        migrations.AddField(
            model_name="cajadolares",
            name="conecta_pesos",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppZorro.cajapesos",
            ),
        ),
        migrations.AlterField(
            model_name="cajadolares",
            name="autor",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cajadolares",
            name="cotiza",
            field=models.FloatField(default=1285),
        ),
        migrations.AlterField(
            model_name="cajapesos",
            name="autor",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cajapesos",
            name="rubro",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="AppZorro.rubros",
            ),
        ),
        migrations.AlterField(
            model_name="cajapesos",
            name="valor_dolar",
            field=models.FloatField(default=1285),
        ),
        migrations.AlterField(
            model_name="obra",
            name="m2_total",
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="fecha",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
