# Generated by Django 4.2 on 2024-08-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AppZorro",
            "0021_cajapesos_conecta_dolares_alter_cajadolares_cotiza_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cajapesos",
            name="cotiza",
            field=models.FloatField(default=1275),
        ),
    ]
