# Generated by Django 4.2 on 2024-08-31 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppZorro", "0022_cajapesos_cotiza"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cajapesos",
            name="valor_dolar",
        ),
    ]
