# Generated by Django 4.2 on 2024-09-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppZorro", "0023_remove_cajapesos_valor_dolar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cajadolares",
            old_name="conecta_pesos",
            new_name="conecta",
        ),
        migrations.RenameField(
            model_name="cajapesos",
            old_name="conecta_dolares",
            new_name="conecta",
        ),
    ]
