# Generated by Django 4.2 on 2024-09-15 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppZorro", "0024_rename_conecta_pesos_cajadolares_conecta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarea",
            name="rubro",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="AppZorro.rubros",
            ),
        ),
        migrations.AlterField(
            model_name="cajadolares",
            name="cotiza",
            field=models.FloatField(default=1235),
        ),
        migrations.AlterField(
            model_name="cajapesos",
            name="cotiza",
            field=models.FloatField(default=1235),
        ),
    ]
